In [1]:
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
# Importing the dataset
dataset = pd.read_csv(r'C:\Users\Abhinav_Kumar21\Documents\MLfiles\Udemy_Training\Machine\Machine Learning\data\Machine+Learning\Machine Learning\Regression\Data.csv')
X = dataset.iloc[:, 1:-1].values
y = dataset.iloc[:, -1].values

In [3]:
print(X)

[[  41.76 1024.07   73.17]
 [  62.96 1020.04   59.08]
 [  39.4  1012.16   92.14]
 ...
 [  74.33 1012.92   36.48]
 [  69.45 1013.86   62.39]
 [  62.52 1017.23   67.87]]


In [4]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [5]:
# Training the Polynomial Regression model on the Training set
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
poly_reg = PolynomialFeatures(degree = 4)
X_poly = poly_reg.fit_transform(X_train)
regressor = LinearRegression()
regressor.fit(X_poly, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [6]:
# Predicting the Test set results
y_pred = regressor.predict(poly_reg.transform(X_test))
np.set_printoptions(precision=2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[431.06 431.23]
 [463.38 460.01]
 [470.46 461.14]
 ...
 [470.28 473.26]
 [443.2  438.  ]
 [466.89 463.28]]


In [7]:
# Evaluating the Model Performance
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

0.8418710285383605